### ISSUE TITLE
Ability Points

### ISSUE THREAD

**Issue by Ogbli** [vvMv/rpgplus#41]
Unlocked at milestones, Used to upgrade and unlock abilities

**Comment by vvMv** [comment]
This is a feature that I would like to add when known what is wanted. I'm thinking each level you get a skill point which can be used to boost a skill in some way? Would need to be preplanned so users can spend their points wisely, and maybe able to reclaim used points? @j08 perhaps you could suggest some kind of skill points obtained by levelling up, or hitting a milestone, what could they be used for?

**Comment by j08** [comment]
Just be a bit careful with this one because what people will do is grind one skill to increase a harder one to grind. I would suggest that the points should only enhance the skill it was earned on. 

2 things that come to mind are the duration of the ability, or the cool down. 

Really one of these things should be happening anyway. At the moment someone with lvl1 dash has the exact same ability as someone who has lvl100 dash. Like the hearts someone who is lvl100 should be able to dash for twice as long. 

If you want to allow the player to be able to be more interactive with the points that they have earned then maybe allow them to either choose to reduce the cool down or to increase the duration. 

As a player I would like to see the abilities get stronger as I level up, as in the duration getting longer. Then have level rewards points that could be spent on something that I can’t just find or make. 
Maybe they could go towards an ability where points is the only way to level it up. Or maybe the could be exchanged for crate keys or enchantments on armour/weapons.

**Comment by j08** [comment]
Dota has so many great abilities you only really need to look to there for inspiration. I would think that as you got to higher levels you become more godly on the server so people who just join the server can't just go round killing people who have been here for years just because they don't have anything to lose.

For example the ability points could go special abilities which would be passives like:
Super thorns: When hit it damages everyone around the player (Britleback)
Blast back: Deafening Blast in one direction or radial.
Stun: Freezes the mob/player for a duration when hit
Immunity: Blocks all damage for XX seconds, with cool down. (eon disk)
Chilly: Reduces the mob or players movement speed down to a crawl on hit.
Magic Block: Make immune from debuff potions and other player's abilities for XX seconds with cool down. 

The other thing I was thinking was maybe you could create a Super Beacon item which wouldn't need the normal pyramid or sky view to activate it. They could then use the ability points to boost their Super Beacon. I don't know if this is possible but the item could be something that they can claim which would either be a structure or just a normal beacon with particles around it to make it different. This beacon could be only mined by the owning player, and the effects will only effect the owning player. It would do things like increase armour, restore hunger and hearts, increase output damage, speed, mining speed, etc. The more ability points the player has the stronger the effects are, and how far they spread out. I'm thinking this would be placed in their home to make it easier to build their home and more survivable against mobs and other players.

**Comment by vvMv** [comment]
Great ideas, for the abilities how about each ability can be leveled up individually to become more powerful and each ability will have a maximum level. You can level these abilities up using points you get from leveling up their respective skills.

As for the beacon thing it's probably more server specific rather than to do with the rpg plugin, it would be very helpful in a lot of cases and might be a good idea to sell for currency. Can you post it under survillas github?

**Comment by j08** [comment]
Well I guess to make it more custom to the player you could earn mining credits that you then can apply to individual mining abilities. So if a player wanted vein mining to last longer they can apply the points to that. If they are interested in hunting for diamond they might want to apply those points for the locator to last longer. As you say, have it capped at a certain level though.

This obviously makes more sense when there is multiple abilities, if there is just one it might seem a bit redundant, but would get the player into the habit of applying points.

**Comment by vvMv** [comment]
fba28facba7c7b9b34de00d220f2180db1eb6b30
