### ISSUE TITLE
Editing attributies without taking points

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#88]
**Description of the feature**
This feature will allow you to edit someone's attributies without taking someone's points. There would be an argument in a command for example -a, so it will look like "/rpg setattribute MrLarkyy_ dash decrease_cooldown 1 -a"

**Comment by vvMv** [comment]
Due to limitations in how point values are calculated this is not currently possible, however unsafe values of attributes are available. This should have no negative effect for regular players, but for admins that want to set their attributes above normal values you may append false as a "safe" parameter to the end of the setattribute command, example: "/rpg setattribute MrLarkyy_ dash decrease_cooldown 100 false"
