### ISSUE TITLE
Custom lvling curve

### ISSUE THREAD

**Issue by TadiklCZE** [vvMv/rpgplus#96]
**Description of the feature**
Add an option that allows you to set a base from where the lvling curve start. Also would be super useful if you add an option to edit the curve ^^

**Comment by vvMv** [comment]
After some consideration with how the curve works, I have decided that there is enough customisation with changing exp values and changing the curve already and changing this will break things more than it's worth. If you want to change how hard it is to level up I would change the experience values in each skill config that are granted so that each level is harder to obtain.
